//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectMarksApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Marks { get; set; }
        public string StudentID { get; set; }
    }
}
